name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    timeout-minutes: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Check neptun.txt
        uses: akosdudas/ahk-action-neptuncheck@master
        if: github.event.before != '0000000000000000000000000000000000000000'
